import './globals.css';
import { Inter } from 'next/font/google';
import React from 'react';
import Header from './header/header';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: { default: 'Home | productname', template: '%s | productname' },
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />{' '}
        {/* This is the header that checks the session and renders appropriate links */}
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
